---
#
# Installing Elasticsearch
#

# Adds the apt-key for Elasticsearch
- name: Add Elasticsearch apt-key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

# Add the Elasticsearch APT-repository
- name: Adding Elasticsearch APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present

# Install Elasticsearch
- name: Update repositories cache and install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes

- command: /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2
  args:
    creates: /usr/share/elasticsearch/plugins/discovery-ec2

- command: /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-user-agent
  args:
    creates: /usr/share/elasticsearch/plugins/ingest-user-agent

- command: /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip
  args:
    creates: /usr/share/elasticsearch/plugins/ingest-geoip

- template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- copy:
    src: jvm.options
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660

# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
    name: elasticsearch
    state: restarted