---
- hosts: elasticsearch_master
  roles:
    - role: java
    - role: elasticsearch
    - role: kibana
    - role: filebeat
    - role: nginx
  vars:
    es_master: true

- hosts: elasticsearch_data
  roles:
    - role: java
    - role: elasticsearch
    - role: kibana
    - role: filebeat
  vars:
    es_master: false
