---
#
# Installing Kibana
#

# Add Kibana APT-repository
- name: Adding Kibana APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present

# Install Kibana
- name: Update repositories cache and install Kibana
  apt:
    name: kibana
    update_cache: yes

- copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644

# Enable Kibana service
- name: Enabling Kibana service
  systemd:
    name: kibana
    enabled: yes
    daemon_reload: yes

# Start Kibana service
- name: Starting Kibana service
  systemd:
    name: kibana
    state: started
